import json
from datetime import datetime
from pathlib import Path


class ReportGenerator:
    """
    Generates professional incident reports from agent analysis results.
    These reports are what a SOC manager or CISO would read.
    """

    def __init__(self, output_dir="./reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate(self, analysis_result: dict) -> str:
        """Generate a full incident report as markdown text."""

        alert = analysis_result["alert"]
        intel = analysis_result["threat_intel"]
        ai_analysis = analysis_result["ai_analysis"]
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

        report = f"""
# 🚨 INCIDENT REPORT
**Report ID:** IR-{alert['alert_id']}  
**Generated:** {generated_at}  
**Classification:** {alert['severity_label']}  
**Status:** Under Investigation

---

## 1. EXECUTIVE SUMMARY
Alert **{alert['alert_id']}** was triggered on host **{alert['hostname']}** at {alert['timestamp']}.
Event type: **{alert['event_type'].replace('_', ' ').title()}**
Severity: **{alert['severity_label']} (Score: {alert['severity_score']})**

---

## 2. ALERT DETAILS

| Field | Value |
|-------|-------|
| Alert ID | {alert['alert_id']} |
| Event Type | {alert['event_type']} |
| Severity | {alert['severity_label']} |
| Source IP | {alert['source_ip']} |
| Destination IP | {alert['destination_ip']} |
| Hostname | {alert['hostname']} |
| Timestamp | {alert['timestamp']} |

---

## 3. MITRE ATT&CK MAPPING

| Field | Value |
|-------|-------|
| Tactic | {alert.get('mitre_tactic', 'Unknown')} |
| Technique | {alert.get('mitre_technique', 'Unknown')} |

---

## 4. THREAT INTELLIGENCE

### VirusTotal
- Malicious Detections: {intel['virustotal'].get('malicious_votes', 'N/A')}
- Country: {intel['virustotal'].get('country', 'Unknown')}
- Verdict: {'⚠️ MALICIOUS' if intel['virustotal'].get('is_malicious') else '✅ CLEAN'}

### AbuseIPDB  
- Abuse Confidence Score: {intel['abuseipdb'].get('abuse_confidence_score', 'N/A')}%
- Total Reports: {intel['abuseipdb'].get('total_reports', 'N/A')}
- ISP: {intel['abuseipdb'].get('isp', 'Unknown')}
- TOR Exit Node: {intel['abuseipdb'].get('is_tor', False)}

---

## 5. AI ANALYST ASSESSMENT

{ai_analysis}

---

## 6. REPORT METADATA
- Generated by: Autonomous SOC Analyst Agent v1.0
- Analysis Engine: GPT-4o
- Report Classification: TLP:AMBER
"""

        # Save report to file
        filename = f"IR-{alert['alert_id']}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.md"
        filepath = self.output_dir / filename

        with open(filepath, "w") as f:
            f.write(report)

        print(f"[REPORT] Saved: {filepath}")
        return report

    def save_as_json(self, analysis_result: dict):
        """Also save raw analysis as JSON for the database."""
        alert_id = analysis_result["alert"]["alert_id"]
        filename = f"IR-{alert_id}.json"
        filepath = self.output_dir / filename

        with open(filepath, "w") as f:
            json.dump(analysis_result, f, indent=2)